### ISSUE TITLE
[Feature Request] - Ntfy/Discord/Slack/Gotify notifications

### ISSUE THREAD

**Issue by steveiliop56** [sergi0g/cup#35]
Hello,

It would be awesome to have the option for Cup to send notifications just like Uptime Kuma. This would require some sort of thread to check for image updates and automatically send notifications but I believe it's a must have for these apps. Unfortunately I can't find any library like shoutrrr for Rust so you will probably have to write your own wrappers around the different APIs but don't worry is very simple. I would recommend [Discohook](https://discohook.org/) for the Discord part.

**Comment by sergi0g** [comment]
Hello @steveiliop56! Thanks for opening this issue!

The README mentions the following:
> Cup cannot directly trigger your integrations. If you want that to happen automatically, please use What's up Docker instead. Cup was created to be simple. The data is there, and it's up to you to retrieve it (e.g. by running `cup check -r` with a cronjob or periodically requesting the `/json` url from the server).

As you mentioned, there is no library that makes this easy in Rust and maintaining such a feature would be hard. It would also require Cup to be stateful, something I am currently hesitant to do, as it would make handling the CLI and the Docker image more complicated. Because of this, I'll have to close this issue as not planned.

However, with some scripting, or an app like [n8n](https://n8n.io/), you can create any automation you like. You could set up notifications, automatically update your images and more! If you have a script, configuration or tutorial you'd like to share with the community, I'll happily include it in the docs, so other users can find it more easily!
